name: Compile Backend

# Exécuter le workflow à chaque push ou pull request sur main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Spring Boot Backend
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Étape 3 : Construire le projet avec Maven
      - name: Build with Maven
        run: mvn clean install

      # Étape 4 : Vérifier que le jar a été créé
      - name: Verify JAR
        run: ls -l target/*.jar
